### ISSUE TITLE
ERROR - Could not load 'guard/concat' or '~/.guard/templates/concat' or find class 

### ISSUE THREAD

**Issue by shinokada** [makevoid/guard-concat#9]
I am getting error when I run guard init. 
I am using Yosemite on OSX and all versions are displayed as followings.

Any idea?

➜ mywebsite sudo gem install guard-concat
Password:
Successfully installed guard-concat-0.0.3
Parsing documentation for guard-concat-0.0.3
1 gem installed
➜  mywebsite  guard init concat
15:06:11 - ERROR - Could not load 'guard/concat' or '~/.guard/templates/concat' or find class Guard::Concat
➜  mywebsite  guard -v
Guard version 2.10.5
➜  mywebsite ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by bransinanderson** [comment]
Same issue, did you find a workaround?

**Comment by makevoid** [comment]
I think there is a fix for this on master that is not yet published to rubygems, for now you may want to modify your Gemfile like this

    gem 'guard-concat', github: "makevoid/guard-concat"

I will soon push the gem to rubygems and notify you (close this ticket)

Please tell me if that fixed the issue, thanks :)

**Comment by shinokada** [comment]
No, it didn't solve it for me.

sudo gem install bundler
created a Gemfile with `gem 'guard-concat', github: "makevoid/guard-concat"`
bundle install
sudo gem install guard-concat
guard init
22:29:09 - ERROR - Could not load 'guard/concat' or '~/.guard/templates/concat' or find class Guard::Concat

Same error.

**Comment by makevoid** [comment]
you can try to run:

```
bundle exec guard init
```

so it will run the bundled version of guard and guard concat

---

you actually don't need to run `guard init`, it's handy but not required. You can get a sample line from here: https://github.com/makevoid/guard-concat#usage and put it in your Guardfile, that's what init does

---

for the records you can also download and install manually the gem from this repo via:

```
git clone https://github.com/makevoid/guard-concat.git
cd guard-concat
gem build guard-concat.gemspec
gem install guard-concat-x.x.x.gem
```

(guard-concat-0.8.0.gem)

enjoy
